# Generated by Django 4.1.1 on 2022-10-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete', '0003_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
